### ISSUE TITLE
Underscore dependency on front end acf form

### ISSUE THREAD

**Issue by PacomeGcom** [mcguffin/acf-field-openstreetmap#86]
Hi ppl,
When using the plugin on a front end form map pin moving/adress bar is not usable. Cause seems to be underscore : 

acf-input-osm.min.js?ver=1.3.5:1 Uncaught ReferenceError: _ is not defined
    at n.set (acf-input-osm.min.js?ver=1.3.5:1:396)
    at h.Model (backbone.min.js?ver=1.4.0:2:4117)
    at n [as constructor] (backbone.min.js?ver=1.4.0:2:23426)
    at new n (backbone.min.js?ver=1.4.0:2:23426)
    at n.initialize (acf-input-osm.min.js?ver=1.3.5:1:4382)
    at h.View (backbone.min.js?ver=1.4.0:2:14139)
    at new n (backbone.min.js?ver=1.4.0:2:23426)
    at HTMLDocument.<anonymous> (acf-input-osm.min.js?ver=1.3.5:1:15476)
    at HTMLDocument.dispatch (jquery.min.js:2:43090)
    at v.handle (jquery.min.js:2:41074)

I've tried to deregister underscore then enqueue it again, CDN, inline, etc. Pretty much everything.

I've also tried to use both ways to display ACF front form with acf_form() and acf_register_form(), no luck there.

Sometime it's working as intended when i double refresh the page, but if i try to use adress bar or move a pin, same message pops up in console and map crash.

Awesome plugin nonetheless.

**Comment by PacomeGcom** [comment]
Found a solution to my problem. _ was unregistered by another script.
